# Relational Database Coursework

**Author:** Jiancheng Zhang

**Username:** root

Students have been supplied this skeleton notebook for completing their F21DF coursework.

This notebook makes use of the [IPython SQL magic](https://github.com/catherinedevlin/ipython-sql) developed by [Catherine Devlin's](http://catherinedevlin.blogspot.com/). Magics are a mechanism within Jupyter to achieve some specific feature within Python such as executing SQL commands over a database. An overview of magics can be found in the [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/01.03-magic-commands.html).

Students are required to complete all sections of this notebook and then submit it according to the supplied instructions.

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Connect-to-the-MACS-Database-Server" data-toc-modified-id="Connect-to-the-MACS-Database-Server-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Connect to the MACS Database Server</a></span></li><li><span><a href="#Database-Design-[10-Marks]" data-toc-modified-id="Database-Design-[10-Marks]-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Database Design [10 Marks]</a></span></li><li><span><a href="#Relational-Schema-[10-Marks]" data-toc-modified-id="Relational-Schema-[10-Marks]-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Relational Schema [10 Marks]</a></span></li><li><span><a href="#Loading-Data-[5-Marks]" data-toc-modified-id="Loading-Data-[5-Marks]-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Loading Data [5 Marks]</a></span></li><li><span><a href="#Querying-the-Database-[20-Marks]" data-toc-modified-id="Querying-the-Database-[20-Marks]-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Querying the Database [20 Marks]</a></span></li></ul></div>

## Connect to the MACS Database Server

If the following commands do not work, then refer to the lab notebooks used in the course.

In [1]:
# Load the SQL magics for jupyter
%load_ext sql

The following cell set the address for the MySQL database server to connect to. The default addess is for MySQL to be installed on the same machine, i.e. `localhost:3306`, as is the case on the MACS Linux VM. The MACS MySQL server address is `mysql-server-1.macs.hw.ac.uk:3306`.

In [2]:
# Set mysql server address
server = "localhost:3306"

In [3]:
# Establish connection to MACS Database Server
from getpass import getpass
username = input('Enter your mysql username: ')
password = getpass(prompt='Enter your mysql password: ')
connection_string = "mysql+pymysql://{username}:{password}@{server}/".format(username=username, password=password, server=server)
%sql $connection_string

Enter your mysql username: root
Enter your mysql password: ········


In [4]:
%sql use WattFashion

 * mysql+pymysql://root:***@localhost:3306/
0 rows affected.


[]

## 1. Database Design [10 Marks]

**ToDo:** Provide the ER diagram for your database. Save your ER diagram in the same directory as this notebook as a png file with the filename `erDiagram.png`.

<img src="erDiagram.png" alt="Drawing" style="width: 850px;"/>

**ToDo:** Give a brief overview of your diagram detailing any design decisions made, and constraints that could not be captured.

This ER diagram has six sections. Customer's email should be unique and address consist of street, city and country, gender is enum. A customer can have many orders, so customer id should as a foreign key in order. An order has received date and maybe a completed date, the received date can't be null. An order can has many garment and a garment can in many orders, this is a many-to-many relationship as well as each garment has its paid price which may has difference from recommanded price, and default by 0.00 which means the customer still not pay for it. A garment has a name, can't be null, a description, can be null, a type and a recommanded price. There are six types that T-shirt, jacket, trouser, coat, sock and shirt, a garment can only be one of them. There are four size for chosen which are S, M, L, XL. A garment can available in each size and a size is available for many garment. But there are only four types, so I decided to put garment id into size table as foreign key and combine garment id and size as primary key that must be unique in size table. In size table, label is size add measurement, and not null. Because there are many colours, so here is another many-to-many relationship, a new table for garment id and colour id will be needed. I decided the colour id domain is 1-99, garment id is 101-999, customer id is 1001-9999 and order number is 10001-99999, all of these are auto increase by 1 each row. Domain constraints, entity constraints, referential constraints and custom constraints are used in the entity relationship scheme.

## 2. Relational Schema [10 Marks]

**ToDo:** Using the following table template, provide the data dictionary for the relational schema you have generated from your ER diagram.

**Garment**

| Attribute | Description | Domain | Null? | Primary Key | Foreign Key
| --- | --- | --- | --- | --- | --- |
|garmentId| ID of garment | INTEGER | N | Y | N |
|name| name of garment | VARCHAR(15) | N | N | N |
|description| how to describe a garment | VARCHAR(100) | Y | N | N |
|type| which type of clothes | ENUM | N | N | N |
|recPrice| recommanded price for sale | DECIMAL(6,2) | N | N | N |

**Size**

| Attribute | Description | Domain | Null? | Primary Key | Foreign Key
| --- | --- | --- | --- | --- | --- |
|s_garmentId| garment id as foreign key here | INTEGER | N | Y | Y |
|abb| abbreviation of different size | ENUM | N | Y | N |
|label| consist of size and meansurement | VARCHAR(50) | N | N | N |
|measurement| the data of each section of a garment | VARCHAR(30) | N | N | N |

**ColourType**

| Attribute | Description | Domain | Null? | Primary Key | Foreign Key
| --- | --- | --- | --- | --- | --- |
|colourId| id of each colour | INTEGER | N | Y | N |
|colour| name of colours | VARCHAR(15) | N | N | N |

**Customer**

| Attribute | Description | Domain | Null? | Primary Key | Foreign Key
| --- | --- | --- | --- | --- | --- |
|cusId| id of customer | INTEGER | N | Y | N |
|email| customer's email | VARCHAR(30) | N | N | N |
|fullname| name of customer | VARCHAR(100) | N | N | N |
|street| which street is a customer living | VARCHAR(100) | Y | N | N |
|city| which city is a customer living | VARCAHR(20) | Y | N | N |
|country| which country is a customer living | VARCHAR(15) | Y | N | N |
|gender| gender of customer | ENUM | N | N | N |

**Order**

| Attribute | Description | Domain | Null? | Primary Key | Foreign Key
| --- | --- | --- | --- | --- | --- |
|orderNum| number of an order | INTEGER | N | Y | N |
|o_cusId| customer id as foreign key | INTEGER | N | N | Y |
|receivedDate| the order received date | DATE | N | N | N |
|completeDate| the data of order finished | DATE | Y | N | N |

**Colour**

| Attribute | Description | Domain | Null? | Primary Key | Foreign Key
| --- | --- | --- | --- | --- | --- |
|c_colourId| colour id as part of primary key as well as foreign key | INTEGER | N | Y | Y |
|c_garmentId| garment id as part of primary key as well as foreign key | INTEGER | N | Y | Y |

**Item**

| Attribute | Description | Domain | Null? | Primary Key | Foreign Key
| --- | --- | --- | --- | --- | --- |
|i_orderNum| order number as foreign key here | INTEGER | N | Y | Y |
|i_garmentId| primary key of size table as foreign key | INTEGER | N | Y | Y |
|i_abb| primary key of size table as foreign key | ENUM | N | Y | Y |
|pricePaid| the customer paid money | DECIMAL(10,2) | Y | N | N |

## 3. Schema Implementation [10 Marks]

**ToDo:** For each table in your relational schema, give the SQL CREATE statement for the table in one cell and the insert statements in a separate cell. Use markdown cells to describe the table and give any design decisions.

Explanation: the garmentId auto increase 1 from 101 and as primary key. The recommended price is a 4 digtials with two decimal number and cannot be null. the type of `type` is ENUM and cannot be null alse. Only garmentId 103 is trouser.

In [5]:
%%sql
CREATE TABLE Garment(
    garmentId INT(3) NOT NULL AUTO_INCREMENT,
    name VARCHAR(15) NOT NULL UNIQUE,
    description VARCHAR(100),
    type ENUM('T-shirt','jacket','trouser','coat','sock','shirt') NOT NULL,
    recPrice DECIMAL(6,2) NOT NULL,
    PRIMARY KEY (garmentId)
)ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=101 ;

 * mysql+pymysql://root:***@localhost:3306/
0 rows affected.


[]

In [6]:
%%sql
INSERT INTO Garment (garmentId, name, description, `type`, recPrice) VALUES
(101, '1aa', 'sdafdsfdsdfs', 'T-shirt', 123.00),
(102, '2bb', 'saflkdsjalfjdskl', 'jacket', 1435.00),
(103, '3cc', 'sahdfkjsdhfakj', 'trouser', 489.00),
(104, '4dd', 'jiogjijfdli', 'coat', 9983.00),
(105, '5ee', 'ioueworurewe', 'sock',87.00),
(106, '6ff', 'xmnczmv,xv', 'shirt', 812.00);

 * mysql+pymysql://root:***@localhost:3306/
6 rows affected.


[]

In [7]:
%%sql
SELECT * FROM Garment

 * mysql+pymysql://root:***@localhost:3306/
6 rows affected.


[(101, '1aa', 'sdafdsfdsdfs', 'T-shirt', Decimal('123.00')),
 (102, '2bb', 'saflkdsjalfjdskl', 'jacket', Decimal('1435.00')),
 (103, '3cc', 'sahdfkjsdhfakj', 'trouser', Decimal('489.00')),
 (104, '4dd', 'jiogjijfdli', 'coat', Decimal('9983.00')),
 (105, '5ee', 'ioueworurewe', 'sock', Decimal('87.00')),
 (106, '6ff', 'xmnczmv,xv', 'shirt', Decimal('812.00'))]

Explanation: garmentId as foreign key and combine with `abb` as primary key. Referential constraint is used in s_garmentId.

In [8]:
%%sql
CREATE TABLE Size(
    s_garmentId INT(3) NOT NULL,
    abb ENUM('S','M','L','XL') NOT NULL,
    label VARCHAR(50) NOT NULL,
    measurement VARCHAR(30) NOT NULL,
    PRIMARY KEY (s_garmentId,abb),
    FOREIGN KEY (s_garmentId) REFERENCES Garment(garmentId) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB  DEFAULT CHARSET=latin1;

 * mysql+pymysql://root:***@localhost:3306/
0 rows affected.


[]

In [9]:
%%sql
INSERT INTO Size (s_garmentId, abb, label, measurement) VALUES
(101, 'S', 'Small 25"waist short arm', '25"chest'),
(101, 'M', 'Medium 26"waist short arm', '26"chest'),
(101, 'L', 'Large 27"waist short arm', '27"chest'),
(102, 'S', 'Small 25"waist short arm', '25"chest'),
(102, 'M', 'Medium 26"waist short arm', '26"chest'),
(102, 'L', 'Large 27"waist short arm', '27"chest'),
(103, 'S', 'Small 25"waist short leg', '25"chest'),
(103, 'M', 'Medium 26"waist short leg', '26"chest'),
(103, 'L', 'Large 27"waist short leg', '27"chest'),
(104, 'S', 'Small 25"waist short arm', '25"chest'),
(104, 'M', 'Medium 26"waist short arm', '26"chest'),
(104, 'L', 'Large 27"waist short arm', '27"chest'),
(105, 'S', 'Small 25"waist short foot', '25"chest'),
(105, 'M', 'Medium 26"waist short foot', '26"chest'),
(105, 'L', 'Large 27"waist short foot', '27"chest'),
(106, 'S', 'Small 25"waist short arm', '25"chest'),
(106, 'M', 'Medium 26"waist short arm', '26"chest'),
(106, 'L', 'Large 27"waist short arm', '27"chest');

 * mysql+pymysql://root:***@localhost:3306/
18 rows affected.


[]

In [10]:
%%sql
SELECT * FROM Size

 * mysql+pymysql://root:***@localhost:3306/
18 rows affected.


[(101, 'S', 'Small 25"waist short arm', '25"chest'),
 (101, 'M', 'Medium 26"waist short arm', '26"chest'),
 (101, 'L', 'Large 27"waist short arm', '27"chest'),
 (102, 'S', 'Small 25"waist short arm', '25"chest'),
 (102, 'M', 'Medium 26"waist short arm', '26"chest'),
 (102, 'L', 'Large 27"waist short arm', '27"chest'),
 (103, 'S', 'Small 25"waist short leg', '25"chest'),
 (103, 'M', 'Medium 26"waist short leg', '26"chest'),
 (103, 'L', 'Large 27"waist short leg', '27"chest'),
 (104, 'S', 'Small 25"waist short arm', '25"chest'),
 (104, 'M', 'Medium 26"waist short arm', '26"chest'),
 (104, 'L', 'Large 27"waist short arm', '27"chest'),
 (105, 'S', 'Small 25"waist short foot', '25"chest'),
 (105, 'M', 'Medium 26"waist short foot', '26"chest'),
 (105, 'L', 'Large 27"waist short foot', '27"chest'),
 (106, 'S', 'Small 25"waist short arm', '25"chest'),
 (106, 'M', 'Medium 26"waist short arm', '26"chest'),
 (106, 'L', 'Large 27"waist short arm', '27"chest')]

Explanation: one colour for one ID.

In [11]:
%%sql
CREATE TABLE ColourType(
    colourId INT(2) NOT NULL AUTO_INCREMENT,
    colour VARCHAR(15) NOT NULL,
    PRIMARY KEY (colourId)
)ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

 * mysql+pymysql://root:***@localhost:3306/
0 rows affected.


[]

In [12]:
%%sql
INSERT INTO ColourType (colourId, colour) VALUES
(1, 'Red'),
(2, 'Yellow'),
(3, 'Black'),
(4, 'Orange'),
(5, 'WHite'),
(6, 'Purple'),
(7, 'green'),
(8, 'Brown'),
(9, 'Dark Blue'),
(10, 'Gray');

 * mysql+pymysql://root:***@localhost:3306/
10 rows affected.


[]

In [13]:
%%sql
SELECT * FROM ColourType

 * mysql+pymysql://root:***@localhost:3306/
10 rows affected.


[(1, 'Red'),
 (2, 'Yellow'),
 (3, 'Black'),
 (4, 'Orange'),
 (5, 'WHite'),
 (6, 'Purple'),
 (7, 'green'),
 (8, 'Brown'),
 (9, 'Dark Blue'),
 (10, 'Gray')]

Explanation: the email must be unique but has to change easily, so I created customer id as the primary key. The address of customer can be null. Customer 1001 and 1003 have unfullfilled order and 1003 has waited a month for order 10006 which is the longest.

In [14]:
%%sql
CREATE TABLE Customer(
    cusId int(4) NOT NULL AUTO_INCREMENT,
    email VARCHAR(30) UNIQUE NOT NULL, 
    fullname VARCHAR(100) NOT NULL,
    street VARCHAR(100),
    city VARCHAR(20),
    country VARCHAR(15),
    gender ENUM('M','F','O') NOT NULL,
    PRIMARY KEY (cusId)
)ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1001 ;

 * mysql+pymysql://root:***@localhost:3306/
0 rows affected.


[]

In [15]:
%%sql
INSERT INTO Customer (cusId, email, fullname, street, city, country, gender) VALUES
(1001, '1092382@qq.com', 'Jusmine Abdse', '123qwe', 'ssdfs', 'China', 'F'),
(1002, '248092340@qq.com', 'dsfs safd', 'we21e', 'dsaf', 'China', 'M'),
(1003, '109348091@qq.com', 'asdfs llsj', 'dsaas2', 'dsafs', 'China', 'O');

 * mysql+pymysql://root:***@localhost:3306/
3 rows affected.


[]

In [16]:
%%sql
SELECT * FROM Customer

 * mysql+pymysql://root:***@localhost:3306/
3 rows affected.


[(1001, '1092382@qq.com', 'Jusmine Abdse', '123qwe', 'ssdfs', 'China', 'F'),
 (1002, '248092340@qq.com', 'dsfs safd', 'we21e', 'dsaf', 'China', 'M'),
 (1003, '109348091@qq.com', 'asdfs llsj', 'dsaas2', 'dsafs', 'China', 'O')]

Explanation: number of order as primary key and customer id as foreign key. I set `completeDate` default null, means every new order that add into should not has a complete date. The creceived date cannot be null. Order 10005 and 10006 received on 2020-09-01.

In [17]:
%%sql
CREATE TABLE `Order`(
    `orderNum` INT(5) NOT NULL AUTO_INCREMENT,
    `o_cusId` INT(4) NOT NULL,
    `receivedDate` date NOT NULL,
    `completeDate` date DEFAULT NULL,
    PRIMARY KEY (`orderNum`),
    FOREIGN KEY (`o_cusId`) REFERENCES Customer(`cusId`) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=10001 ;

 * mysql+pymysql://root:***@localhost:3306/
0 rows affected.


[]

In [18]:
%%sql
INSERT INTO `Order` (orderNum, o_cusId, receivedDate, completeDate)VALUES
(10001, 1001, '2020-04-22', NULL),
(10002, 1001, '2020-04-23', '2020-05-12'),
(10003, 1001, '2020-04-24', NULL),
(10004, 1002, '2020-07-11', '2020-08-09'),
(10005, 1002, '2020-09-01', '2020-09-23'),
(10006, 1003, '2020-09-01', '2020-10-01'),
(10007, 1003, '2020-10-02', NULL);

 * mysql+pymysql://root:***@localhost:3306/
7 rows affected.


[]

In [19]:
%%sql
SELECT * FROM `Order`

 * mysql+pymysql://root:***@localhost:3306/
7 rows affected.


[(10001, 1001, datetime.date(2020, 4, 22), None),
 (10002, 1001, datetime.date(2020, 4, 23), datetime.date(2020, 5, 12)),
 (10003, 1001, datetime.date(2020, 4, 24), None),
 (10004, 1002, datetime.date(2020, 7, 11), datetime.date(2020, 8, 9)),
 (10005, 1002, datetime.date(2020, 9, 1), datetime.date(2020, 9, 23)),
 (10006, 1003, datetime.date(2020, 9, 1), datetime.date(2020, 10, 1)),
 (10007, 1003, datetime.date(2020, 10, 2), None)]

Explanation: colour id and garment id are both primary key and foreign key, a garment can has many colours. Only garment 101 has more than 5 colours.

In [20]:
%%sql
CREATE TABLE Colour(
    c_colourId int(2) NOT NULL,
    c_garmentId int(3) NOT NULL,
    PRIMARY KEY(c_colourId,c_garmentId),
    FOREIGN KEY (c_colourId) REFERENCES ColourType(colourId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (c_garmentId) REFERENCES Garment(garmentId) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB  DEFAULT CHARSET=latin1 ;

 * mysql+pymysql://root:***@localhost:3306/
0 rows affected.


[]

In [21]:
%%sql
INSERT INTO Colour (c_colourId, c_garmentId)VALUES
(1,101),
(2,101),
(3,101),
(6,101),
(8,101),
(9,101),
(2,102),
(10,102),
(3,102),
(7,103),
(4,103),
(3,104),
(9,105),
(1,106),
(3,106),
(4,106),
(7,106);

 * mysql+pymysql://root:***@localhost:3306/
17 rows affected.


[]

In [22]:
%%sql
SELECT * FROM Colour

 * mysql+pymysql://root:***@localhost:3306/
17 rows affected.


[(1, 101),
 (1, 106),
 (2, 101),
 (2, 102),
 (3, 101),
 (3, 102),
 (3, 104),
 (3, 106),
 (4, 103),
 (4, 106),
 (6, 101),
 (7, 103),
 (7, 106),
 (8, 101),
 (9, 101),
 (9, 105),
 (10, 102)]

Explanation: because an order may has many garments, so I created a item table and another attribute is `pricePaid`. the primary key from `Size` table as foreign key here. 10001 and 10003 orders contain trouser garment.

In [23]:
%%sql
CREATE TABLE `Item`(
    `i_orderNum` int(5) NOT NULL,
    `i_garmentId` int(3) NOT NULL,
    `i_abb` ENUM('S','M','L','XL') NOT NULL,
    `pricePaid` DECIMAL(10,2) DEFAULT 0.00,
    PRIMARY KEY (`i_orderNum`,`i_garmentId`,`i_abb`),
    FOREIGN KEY (`i_orderNum`) REFERENCES `Order`(`orderNum`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`i_garmentId`,`i_abb`) REFERENCES `Size`(`s_garmentId`,`abb`) ON DELETE CASCADE ON UPDATE CASCADE
    
)ENGINE=InnoDB  DEFAULT CHARSET=latin1;

 * mysql+pymysql://root:***@localhost:3306/
0 rows affected.


[]

In [24]:
%%sql
INSERT INTO Item (i_orderNum, i_garmentId, i_abb, pricePaid)VALUES
(10001, 101, 'S', '24.00'),
(10001, 102, 'S', '361.00'),
(10001, 103, 'L', '1000.00'),
(10001, 104, 'S', '501.00'),
(10001, 105, 'M', '234.00'),
(10001, 106, 'S', '92.00'),
(10002, 106, 'L', '123.00'),
(10003, 103, 'M', '255.00'),
(10004, 102, 'S', '9023.00'),
(10005, 101, 'L', '1000.00'),
(10005, 102, 'M', '1000.00'),
(10005, 105, 'S', '1000.00'),
(10006, 106, 'S', '1000.00'),
(10006, 104, 'L', '1000.00'),
(10007, 102, 'M', '327.00');

 * mysql+pymysql://root:***@localhost:3306/
15 rows affected.


[]

In [25]:
%%sql
SELECT * FROM Item

 * mysql+pymysql://root:***@localhost:3306/
15 rows affected.


[(10001, 101, 'S', Decimal('24.00')),
 (10001, 102, 'S', Decimal('361.00')),
 (10001, 103, 'L', Decimal('1000.00')),
 (10001, 104, 'S', Decimal('501.00')),
 (10001, 105, 'M', Decimal('234.00')),
 (10001, 106, 'S', Decimal('92.00')),
 (10002, 106, 'L', Decimal('123.00')),
 (10003, 103, 'M', Decimal('255.00')),
 (10004, 102, 'S', Decimal('9023.00')),
 (10005, 101, 'L', Decimal('1000.00')),
 (10005, 102, 'M', Decimal('1000.00')),
 (10005, 105, 'S', Decimal('1000.00')),
 (10006, 104, 'L', Decimal('1000.00')),
 (10006, 106, 'S', Decimal('1000.00')),
 (10007, 102, 'M', Decimal('327.00'))]

## 4. Querying the Database [20 Marks]
Populate each of the cells below with the required SQL query.

### a. Provide the name and email of all customers who have an unfulfilled order.

In [26]:
%%sql
SELECT DISTINCT C.email, C.fullname 
FROM Customer AS C,`Order` AS O
WHERE ISNULL(O.completeDate) AND C.cusId=O.o_cusId

 * mysql+pymysql://root:***@localhost:3306/
2 rows affected.


[('1092382@qq.com', 'Jusmine Abdse'), ('109348091@qq.com', 'asdfs llsj')]

### b. Give the names of garments that are available in 5 or more colours.

In [27]:
%%sql
SELECT G.name
FROM Garment AS G,Colour AS C
WHERE G.garmentId=C.c_garmentId
GROUP BY C.c_garmentId
HAVING COUNT(C.c_garmentId)>=5

 * mysql+pymysql://root:***@localhost:3306/
1 rows affected.


[('1aa',)]

### c. Provide the order numbers of orders that do not contain trousers.

In [28]:
%%sql
SELECT DISTINCT i_orderNum
FROM Item
WHERE i_orderNum NOT IN(
SELECT DISTINCT a.i_orderNum
FROM Item a INNER JOIN (SELECT  I.i_garmentId
FROM Item AS I, Garment AS G
WHERE I.i_garmentId=G.garmentId
AND G.type = 'trouser')b ON b.i_garmentId = a.i_garmentId)


 * mysql+pymysql://root:***@localhost:3306/
5 rows affected.


[(10002,), (10004,), (10005,), (10006,), (10007,)]

### d. What was the total income from orders received on 1 September 2020?

In [29]:
%%sql
SELECT SUM(I.pricePaid) AS totalIncome
FROM Item AS I,`Order` AS O
WHERE O.receivedDate='2020-09-01' AND I.i_orderNum=O.orderNum

 * mysql+pymysql://root:***@localhost:3306/
1 rows affected.


[(Decimal('5000.00'),)]

### e. Of the fulfilled orders, what is the name of the customer(s) who had to wait the longest?

In [30]:
%%sql
SELECT C.fullname
FROM Customer AS C, `Order` AS O
WHERE C.cusId=O.o_cusId AND NOT(ISNULL(O.completeDate))
ORDER BY DATEDIFF(O.completeDate,O.receivedDate) DESC
LIMIT 1

 * mysql+pymysql://root:***@localhost:3306/
1 rows affected.


[('asdfs llsj',)]